---
micronaut:
  application:
    name: persistence

---
datasources.default: {}
---
datasources:
  default:
    default:
      url: ${JDBC_URL:`jdbc:postgresql://localhost/persistence`}
      username: ${JDBC_USER:postgres}
      password: ${JDBC_PASSWORD:postgres}
jpa:
  default:
    packages-to-scan:
      - 'example.micronaut.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
